---
pid: /home/deploy/tmp/pids/thin.pid
log: /home/deploy/log/thin.log
timeout: 30
wait: 30
max_conns: 1024
max_persistent_conns: 512
threaded: true
no-epoll: true
tag: laundromat
chdir: /home/deploy/apps/laundromat/current
user: deploy
group: deploy
port: 3000
servers: 2
address: 127.0.0.1
environment: production
daemonize: true
